workflows:
  android-release:
    name: Simple Android Release Build
    max_build_duration: 20
    scripts:
      - name: Build APK Release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
